# Generated by Django 6.0 on 2025-12-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupy, do których należy ten użytkownik. Użytkownik otrzyma wszystkie uprawnienia przyznane każdej z jego grup.', related_name='%(app_label)s_%(class)s_groups', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specyficzne uprawnienia dla tego użytkownika.', related_name='%(app_label)s_%(class)s_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
