# Generated by Django 5.2.8 on 2025-11-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Ustaw 0, aby wyłączyć limit czasu.', verbose_name='Limit czasu (w minutach)'),
        ),
    ]
