# Generated by Django 5.2.8 on 2025-11-17 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_time_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Udostępnij dla'),
        ),
    ]
