# Generated by Django 5.2.7 on 2025-11-17 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Wynik (%)')),
                ('correct_count', models.IntegerField(verbose_name='Poprawne odpowiedzi')),
                ('total_questions', models.IntegerField(verbose_name='Liczba pytań')),
                ('time_over', models.BooleanField(default=False, verbose_name='Przekroczono czas')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data podejścia')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Próba (Attempt)',
                'verbose_name_plural': 'Próby (Attempts)',
                'ordering': ['-timestamp'],
            },
        ),
    ]
