# Generated by Django 5.0.6 on 2025-11-30 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Udostępnij dla (użytkownicy)'),
        ),
        migrations.CreateModel(
            name='QuizGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa grupy')),
                ('members', models.ManyToManyField(related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Członkowie grupy')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Grupa użytkowników',
                'verbose_name_plural': 'Grupy użytkowników',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_quizzes', to='quizzes.quizgroup', verbose_name='Udostępnij dla (grupy)'),
        ),
    ]
