# Generated by Django 5.2.8 on 2025-11-30 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_shared_with_quizgroup_quiz_shared_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Udostępnij do edycji (Edytujący)'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Czy poprawna'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Treść odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='Wyjaśnienie'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Jednokrotny wybór'), ('MULTIPLE', 'Wielokrotny wybór')], default='SINGLE', max_length=10, verbose_name='Typ pytania'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Treść pytania'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_quizzes', to='quizzes.quizgroup', verbose_name='Udostępnij grupom (Tylko rozwiązywanie)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Udostępnij do rozwiązywania (Przeglądający)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Publiczny'), ('PRIVATE', 'Prywatny')], default='PRIVATE', max_length=10, verbose_name='Widoczność'),
        ),
    ]
