# Generated by Django 5.2.8 on 2025-11-30 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quiz_editors_alter_answer_is_correct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='shared_groups',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='shared_with',
        ),
        migrations.CreateModel(
            name='QuizGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VIEWER', 'Może rozwiązywać'), ('EDITOR', 'Może edytować (członkowie)')], default='VIEWER', max_length=10, verbose_name='Uprawnienie')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizgroup', verbose_name='Grupa')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Uprawnienie grupy',
                'unique_together': {('quiz', 'group')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='groups_permissions',
            field=models.ManyToManyField(blank=True, related_name='quiz_access', through='quizzes.QuizGroupPermission', to='quizzes.quizgroup', verbose_name='Uprawnienia grup'),
        ),
        migrations.CreateModel(
            name='QuizUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VIEWER', 'Może rozwiązywać'), ('EDITOR', 'Może edytować')], default='VIEWER', max_length=10, verbose_name='Uprawnienie')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Uprawnienie użytkownika',
                'unique_together': {('quiz', 'user')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='users_permissions',
            field=models.ManyToManyField(blank=True, related_name='quiz_access', through='quizzes.QuizUserPermission', to=settings.AUTH_USER_MODEL, verbose_name='Uprawnienia użytkowników'),
        ),
    ]
