# Generated by Django 5.0.6 on 2025-12-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_remove_quiz_editors_remove_quiz_shared_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='instant_feedback',
            field=models.BooleanField(default=False, help_text='Jeśli zaznaczone, użytkownik zobaczy poprawne odpowiedzi po każdym pytaniu.', verbose_name='Natychmiastowe odpowiedzi'),
        ),
    ]
