# Generated by Django 5.0.6 on 2025-12-04 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quiz_instant_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions_count_limit',
            field=models.IntegerField(default=10, help_text='Ustal, ile pytań ma zostać wylosowanych do jednego podejścia (zakres: 1-30).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Liczba pytań w podejściu'),
        ),
    ]
